In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Processed.csv')

In [3]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
df.head()

,Source,Severity,Start_Time,Street,City,County,State,Zipcode,Airport_Code,Temperature(F),...,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,weather_Condition,Day_type
0,Source2,3,2016-02-07 23:46:00,I-70 E,Dayton,Montgomery,OH,45424,KFFO,36.9,...,False,False,False,False,False,False,False,False,Rain,Night
1,Source2,2,2016-02-08 00:07:59,Brice Rd,Reynoldsburg,Franklin,OH,43068,KCMH,37.9,...,False,False,False,False,False,False,False,False,Rain,Night
2,Source2,2,2016-02-08 00:49:27,State Route 32,Williamsburg,Clermont,OH,45176,KI69,36.0,...,False,False,False,False,False,False,True,False,Overcast,Night
3,Source2,3,2016-02-08 01:23:34,I-75 S,Dayton,Montgomery,OH,45417,KDAY,35.1,...,False,False,False,False,False,False,False,False,Cloudy,Night
4,Source2,2,2016-02-08 01:39:07,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,KMGY,36.0,...,False,False,False,False,False,False,True,False,Cloudy,Night

In [5]:
severe_accidents = df[df['Severity'] == 4]

# Count the occurrences of each unique 'County' value
severe_count_by_county = severe_accidents['County'].value_counts()

# Find the county with the most severe accidents
most_severe_county = severe_count_by_county.idxmax()
most_severe_accidents = severe_count_by_county.max()

In [6]:
print(f"The county with the most severe accidents (Severity=4) is {most_severe_county} with {most_severe_accidents} severe accidents.")

The county with the most severe accidents (Severity=4) is Fulton with 458 severe accidents.